INSERT INTO role (name) VALUES ('ROLE_CUSTOMER');
INSERT INTO role (name) VALUES ('ROLE_PROVIDER');
INSERT INTO role (name) VALUES ('ROLE_ADMIN');

INSERT INTO banks (name) VALUES ('Vietcombank');
INSERT INTO banks (name) VALUES ('DongA Bank');
INSERT INTO banks (name) VALUES ('Agribank');
INSERT INTO banks (name) VALUES ('BIDV');
INSERT INTO banks (name) VALUES ('VietinBank');
INSERT INTO banks (name) VALUES ('VPBank');
INSERT INTO banks (name) VALUES ('MB bank');
INSERT INTO banks (name) VALUES ('ACB');
INSERT INTO banks (name) VALUES ('VietinBank');
INSERT INTO banks (name) VALUES ('VPBank');
INSERT INTO banks (name) VALUES ('MB bank');
INSERT INTO banks (name) VALUES ('ACB');


INSERT INTO status(name) VALUES ('WAITING');
INSERT INTO status(name) VALUES ('ACCEPT');
INSERT INTO status(name) VALUES ('REFUSE');

INSERT INTO province(name) VALUES  ('An Giang');
INSERT INTO province(name) VALUES  ('Bạc Liêu');
INSERT INTO province(name) VALUES  ('Bắc Cạn');
INSERT INTO province(name) VALUES  ('Bắc Giang');
INSERT INTO province(name) VALUES  ('Bắc Ninh');
INSERT INTO province(name) VALUES  ('Bến Tre');
INSERT INTO province(name) VALUES  ('Bình Dương');
INSERT INTO province(name) VALUES  ('Bình Định');
INSERT INTO province(name) VALUES  ('Bình Phước');
INSERT INTO province(name) VALUES  ('Bình Thuận');
INSERT INTO province(name) VALUES  ('Cà Mau');
INSERT INTO province(name) VALUES  ('Cao Bằng');
INSERT INTO province(name) VALUES  ('Cần Thơ');
INSERT INTO province(name) VALUES  ('Đà Nẵng');
INSERT INTO province(name) VALUES  ('Daklak');
INSERT INTO province(name) VALUES  ('Đồng Nai');
INSERT INTO province(name) VALUES  ('Đồng Tháp');
INSERT INTO province(name) VALUES  ('Gia Lai');
INSERT INTO province(name) VALUES  ('Hà Giang');
INSERT INTO province(name) VALUES  ('Hà Nam');
INSERT INTO province(name) VALUES  ('Hà Nội');
INSERT INTO province(name) VALUES  ('Hà Tĩnh');
INSERT INTO province(name) VALUES  ('Hải Dương');
INSERT INTO province(name) VALUES  ('Hải Phòng');
INSERT INTO province(name) VALUES  ('Hòa Bình');
INSERT INTO province(name) VALUES  ('Hưng Yên');
INSERT INTO province(name) VALUES  ('Hồ Chí Minh');
INSERT INTO province(name) VALUES  ('Khánh Hòa');
INSERT INTO province(name) VALUES  ('Kiên Giang');
INSERT INTO province(name) VALUES  ('Kon Tum');
INSERT INTO province(name) VALUES  ('Lai Châu');
INSERT INTO province(name) VALUES  ('Lạng Sơn');
INSERT INTO province(name) VALUES  ('Lào Cai');
INSERT INTO province(name) VALUES  ('Lâm Đồng');
INSERT INTO province(name) VALUES  ('Long An');
INSERT INTO province(name) VALUES  ('Nam Định');
INSERT INTO province(name) VALUES  ('Nghệ An');
INSERT INTO province(name) VALUES  ('Ninh Bình');
INSERT INTO province(name) VALUES  ('Ninh Thuận');
INSERT INTO province(name) VALUES  ('Phú Thọ');
INSERT INTO province(name) VALUES  ('Phú Yên');
INSERT INTO province(name) VALUES  ('Quảng Bình');
INSERT INTO province(name) VALUES  ('Quảng Nam');
INSERT INTO province(name) VALUES  ('Quảng Ngãi');
INSERT INTO province(name) VALUES  ('Quảng Ninh');
INSERT INTO province(name) VALUES  ('Sóc Trăng');
INSERT INTO province(name) VALUES  ('Sơn La');
INSERT INTO province(name) VALUES  ('Tây Ninh');
INSERT INTO province(name) VALUES  ('Thái Bình');
INSERT INTO province(name) VALUES  ('Thái Nguyên');
INSERT INTO province(name) VALUES  ('Thanh Hóa');
INSERT INTO province(name) VALUES  ('Thừa Thiên Huế');
INSERT INTO province(name) VALUES  ('Tiền Giang');
INSERT INTO province(name) VALUES  ('Trà Vinh');
INSERT INTO province(name) VALUES  ('Tuyên Quang');
INSERT INTO province(name) VALUES  ('Vĩnh Long');
INSERT INTO province(name) VALUES  ('Vĩnh Phúc');
INSERT INTO province(name) VALUES  ('Yên Bái');

INSERT INTO categories(name) VALUES ('Du lịch sinh thái');
INSERT INTO categories(name) VALUES ('Du lịch văn hóa');
INSERT INTO categories(name) VALUES ('Du lịch nghỉ dưỡng');
INSERT INTO categories(name) VALUES ('Du lịch giải trí');
INSERT INTO categories(name) VALUES ('Du lịch thể thao');
INSERT INTO categories(name) VALUES ('Du lịch khám phá');
INSERT INTO categories(name) VALUES ('Du lịch mạo hiểm');
INSERT INTO categories(name) VALUES ('Du lịch kết hợp');

INSERT INTO account (email, password, username ,role_id, create_at) VALUES ('admin@gmail.com', '123456789', 'hoang', 3 , '2022-05-05');
INSERT INTO account (email, password, username ,role_id, create_at) VALUES ('dulichdanang@gmail.com', '123456789', 'hoang1', 2 , '2022-05-05');
INSERT INTO account (email, password, username ,role_id, create_at) VALUES ('hoangusa082@gmail.com', '123456789', 'hoang2', 1 , '2022-05-05');

INSERT INTO admin (account_id, percent) VALUES (1, 10);
INSERT INTO provider (account_id, address, bank_id, bank_number, name_company, owner, phone_number, status_id) VALUES (2 ,'83, Phạm Như Xương, Liên Chiểu, Đà Nẵng', 1, '0110675830' ,'Công ty du lịch Đà Nẵng' , 'Đoàn Tứ', '19002014', 2 );
INSERT INTO customer (address, full_name, phone_number, account_id, is_delete) VALUES ('82, Phạm Như Xương, Liên Chiểu, Đà Nẵng', 'Đoàn Văn Hoàng' ,'0339905697', 3, false);